services:
  - type: web
    name: ibtikar-backend
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: sh -c "cd /opt/render/project/src && export PYTHONPATH=/opt/render/project/src:$PYTHONPATH && uvicorn server.backend.api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free

